### ISSUE TITLE
Source file missing

### ISSUE THREAD

**Issue by Idja88** [GeorgGrebenyuk/TIM-analytic_tools_MGUU_VC_cource#1]
В программе курса в главе 5 идёт указание на получение информации из файла "rme_advanced_sample_project.ifc", но данного файла в папке DataExamples нет.

**Comment by GeorgGrebenyuk** [comment]
Добрый день, приложил здесь https://github.com/GeorgGrebenyuk/TIM-analytic_tools_MGUU_VC_cource/releases/tag/files, часть файлов не публиковалась из-за наличия чужих авторских прав на модели, этот вроде немецкий, из каких-то примеров, выложил, не помню уже почему тогда не публиковался.

**Comment by Idja88** [comment]
Понял, спасибо!
